import React, { useEffect, useState } from 'react';
import { ArrowRight, Check, ShieldAlert, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../../services/api';
import type { ApiResponse, LeaveRequest } from '../../types';
import { useToast } from '../../components/common/Toast';
import { Button, EmptyState, LoadingState, PageHeader, StatusBadge, SurfaceCard } from '../../components/ui';

export const ManagerDashboardPage: React.FC = () => {
  const { showToast } = useToast();
  const [loading, setLoading] = useState(true);
  const [overview, setOverview] = useState<any>(null);
  const [pendingLeaves, setPendingLeaves] = useState<LeaveRequest[]>([]);
  const fetchManagerData = async () => { setLoading(true); try { const [overviewRes, leaveRes] = await Promise.all([api.get<ApiResponse<any>>('/admin/reports/dashboard'), api.get<ApiResponse<LeaveRequest[]>>('/leave-requests?status=pending')]); if (overviewRes.data.success) setOverview(overviewRes.data.data.kpi); if (leaveRes.data.success) setPendingLeaves(leaveRes.data.data); } catch (error) { console.error('Error fetching manager dashboard:', error); } finally { setLoading(false); } };
  useEffect(() => { fetchManagerData(); }, []);
  const handleApprove = async (id: string) => { try { const res = await api.put<ApiResponse<any>>(`/leave-requests/${id}/approve`, { responseNote: 'Quản lý đã duyệt đơn nghỉ phép' }); if (res.data.success) { showToast('Đã duyệt đơn nghỉ phép thành công', 'success'); fetchManagerData(); } } catch (error: any) { showToast(error.response?.data?.message || 'Duyệt đơn thất bại', 'error'); } };
  const handleReject = async (id: string) => { try { const res = await api.put<ApiResponse<any>>(`/leave-requests/${id}/reject`, { responseNote: 'Không thể bố trí người trực thay thế' }); if (res.data.success) { showToast('Đã từ chối đơn nghỉ phép', 'info'); fetchManagerData(); } } catch (error: any) { showToast(error.response?.data?.message || 'Từ chối thất bại', 'error'); } };
  if (loading) return <LoadingState />;
  const cards = [{ label: 'Tổng nhân viên', value: overview?.totalEmployees || 0 }, { label: 'Đi làm hôm nay', value: overview?.staffWorkingToday || 0 }, { label: 'Đi muộn hôm nay', value: overview?.staffLateToday || 0 }, { label: 'Đơn nghỉ chờ duyệt', value: overview?.pendingLeaves || 0 }, { label: 'Booking hôm nay', value: overview?.todayBookings || 0 }, { label: 'Tổng sân thể thao', value: overview?.totalCourts || 0 }];
  return <div className="space-y-8"><PageHeader eyebrow="Operations desk" title="Bàn giao & vận hành ca trực" description="Theo dõi nhân sự trong ngày, kiểm soát ca trực và duyệt đơn nghỉ phép." /><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{cards.map((card, index) => <SurfaceCard key={card.label} className="p-4"><p className="text-[10px] font-bold uppercase tracking-[0.08em] text-[var(--sb-ink-3)]">{card.label}</p><p className={`mt-3 text-2xl font-extrabold ${index === 1 ? 'text-[var(--sb-success)]' : index === 2 || index === 3 ? 'text-[var(--sb-warning)]' : 'text-[var(--sb-ink)]'}`}>{card.value}</p></SurfaceCard>)}</div><SurfaceCard as="section" className="overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-[var(--sb-line)] p-5 sm:flex-row sm:items-center sm:px-6"><div className="flex items-center gap-3"><ShieldAlert className="h-5 w-5 text-[var(--sb-warning)]" /><div><h2 className="text-base font-bold text-[var(--sb-ink)]">Đơn xin nghỉ cần xét duyệt</h2><p className="mt-1 text-xs text-[var(--sb-ink-3)]">{pendingLeaves.length} đơn đang chờ xử lý</p></div></div><Link to="/admin/leaves" className="inline-flex items-center gap-1 text-xs font-bold text-[var(--sb-accent)] hover:underline">Xem tất cả <ArrowRight className="h-3.5 w-3.5" /></Link></div>{pendingLeaves.length === 0 ? <EmptyState title="Không có đơn đang chờ duyệt" description="Khu vực vận hành đang sạch." /> : <div className="divide-y divide-[var(--sb-line)]">{pendingLeaves.map((item) => <article key={item._id} className="flex flex-col justify-between gap-5 p-5 transition-colors hover:bg-[#fffafa] sm:flex-row sm:items-center sm:px-6"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold text-[var(--sb-ink)]">{item.employee?.fullName}</h3><span className="font-mono text-[10px] text-[var(--sb-ink-3)]">{item.employee?.employeeCode}</span><StatusBadge tone="warning">{item.type.replace(/_/g, ' ')}</StatusBadge></div><p className="mt-2 text-xs text-[var(--sb-ink-2)]">Nghỉ từ <strong>{item.startDate}</strong> đến <strong>{item.endDate}</strong></p><p className="mt-1 line-clamp-1 text-xs italic text-[var(--sb-ink-3)]">{item.reason}</p></div><div className="flex shrink-0 items-center gap-2"><Button tone="quiet" onClick={() => handleReject(item._id)}><X className="h-3.5 w-3.5 text-[var(--sb-danger)]" /> Từ chối</Button><Button tone="accent" onClick={() => handleApprove(item._id)}><Check className="h-3.5 w-3.5" /> Duyệt đơn</Button></div></article>)}</div>}</SurfaceCard></div>;
};
